/// Flutter icons AquaHub
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AquaHub
///      fonts:
///       - asset: fonts/AquaHub.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AquaHub {
  AquaHub._();

  static const _kFontFam = 'AquaHub';

  static const IconData buyer = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData shop = const IconData(0xe804, fontFamily: _kFontFam);
}
